-- ==========================================
-- PHASE 12: D2D Route Optimization OS
-- Core Foundation Tables
-- ==========================================

-- 1. Territory Zones
-- The geographical areas that dictate scheduling and D2D saturation efforts.
CREATE TABLE IF NOT EXISTS public.territory_zones (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    name TEXT NOT NULL,
    color TEXT DEFAULT '#1D3B34', -- Pathway Green default
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Customers
-- The entity responsible for billing and communication.
CREATE TABLE IF NOT EXISTS public.customers (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Properties
-- The physical location linked to a zone. If a customer moves, the property remains on the route.
CREATE TABLE IF NOT EXISTS public.properties (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    address TEXT NOT NULL,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    territory_zone_id UUID REFERENCES public.territory_zones(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Service Agreements
-- The recurring contract linking a customer to a property.
CREATE TABLE IF NOT EXISTS public.service_agreements (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    property_id UUID REFERENCES public.properties(id) ON DELETE CASCADE,
    customer_id UUID REFERENCES public.customers(id) ON DELETE CASCADE,
    originated_by_rep_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    recurring_price DECIMAL(10, 2) NOT NULL,
    frequency TEXT NOT NULL, -- e.g., 'bi-monthly', 'quarterly', 'monthly'
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Service Tickets
-- Individual jobs generated by an agreement or ad-hoc requests (like the Initial Flush).
CREATE TABLE IF NOT EXISTS public.service_tickets (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    agreement_id UUID REFERENCES public.service_agreements(id) ON DELETE CASCADE,
    scheduled_start TIMESTAMP WITH TIME ZONE,
    scheduled_end TIMESTAMP WITH TIME ZONE,
    assigned_tech_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    type TEXT DEFAULT 'recurring' CHECK (type IN ('initial', 'recurring', 'reservice')),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'skipped', 'cancelled')),
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE public.territory_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_tickets ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read and insert for now (Admin controls happen at the UI level or through more strict policies later)
CREATE POLICY "Enable all for authenticated users" ON public.territory_zones FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.customers FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.properties FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.service_agreements FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.service_tickets FOR ALL TO authenticated USING (true);
